spring:
  datasource:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:log4jdbc:h2:file:./target/db/customer
    #url: jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    sql-script-encoding: utf8
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate

  thymeleaf:
    mode: HTML

security:
  basic:
    enabled: false
